In [1]:
import pymssql          # conector entre Python y SQL Server
import pandas as pd     # organiza los resultados en tablas (DataFrame)
 
# se abre la conexion con la base 'comercio'
con = pymssql.connect(server="db", user="sa",
                      password="TuClave_Fuerte123",
                      database="comercio")
 
print("Conexión establecida")

Conexión establecida

In [5]:
# las 5 mayores
df = pd.read_sql("SELECT TOP (5) venta_id, categoria, valor "
                 "FROM ventas ORDER BY valor DESC", con)
display(df)
 
# las 5 siguientes (pagina dos)
df2 = pd.read_sql("SELECT venta_id, categoria, valor FROM ventas "
                  "ORDER BY valor DESC "
                                    "OFFSET 5 ROWS FETCH NEXT 5 ROWS ONLY", con)
display(df2)

   venta_id   categoria      valor
0        45  Tecnología  2553000.0
1        23  Tecnología  2346000.0
2        17  Tecnología  2041000.0
3        40  Tecnología  1812000.0
4         2  Tecnología  1632000.0

   venta_id   categoria      valor
0        38  Tecnología  1536000.0
1         5  Tecnología  1487000.0
2        22  Tecnología  1438000.0
3        47  Tecnología  1321000.0
4        46  Tecnología  1213000.0

In [2]:
con.close()
print("Conexión cerrada")

Conexión cerrada